// SPDX-License-Identifier: Apache-2.0
// Auto-generated behavioral test for element: MetaGen
//
// The kernel was generated by openclicknp-cc; we link it in via the
// CMake `openclicknp_element_test()` helper. The test spawns the kernel
// in a thread, drives canned flits through its input ports, and asserts
// on the resulting output stream.
#include "element_test_harness.hpp"

using namespace openclicknp;
using namespace openclicknp::test;

extern "C" void kernel_u(
    SwStream& in_1,
    SwStream& out_1,
    SwStream& out_2,
    std::atomic<bool>& _stop
);

int main() {
    SwStream in_1(64);
    SwStream out_1(64);
    SwStream out_2(64);

    KernelHarness h;
    h.start(kernel_u, std::ref(in_1), std::ref(out_1), std::ref(out_2), std::ref(h.stop));

    // MetaGen forwards flits and emits a metadata flit periodically.
    auto pusher = std::thread([&]() {
        for (int i = 0; i < 16; ++i) in_1.write(make_flit(i));
    });
    auto a = drain(out_1, 16);
    pusher.join();
    ELEM_ASSERT(a.size() >= 8u, "MetaGen should forward most flits");

    h.run_for(50ms);
    ELEM_PASS("MetaGen");
}
