// SPDX-License-Identifier: Apache-2.0
// Auto-generated behavioral test for element: FlowTupleParser
//
// The kernel was generated by openclicknp-cc; we link it in via the
// CMake `openclicknp_element_test()` helper. The test spawns the kernel
// in a thread, drives canned flits through its input ports, and asserts
// on the resulting output stream.
#include "element_test_harness.hpp"

using namespace openclicknp;
using namespace openclicknp::test;

extern "C" void kernel_u(
    SwStream& in_1,
    SwStream& out_1,
    SwStream& out_2,
    std::atomic<bool>& _stop
);

int main() {
    SwStream in_1(64);
    SwStream out_1(64);
    SwStream out_2(64);

    KernelHarness h;
    h.start(kernel_u, std::ref(in_1), std::ref(out_1), std::ref(out_2), std::ref(h.stop));

    // Construct a synthetic flit with Eth+IPv4 header bytes and check it
    // parses without crashing.
    flit_t f{};
    uint8_t buf[32] = {0};
    buf[14+9] = 6;       // proto = TCP
    buf[14+12] = 10; buf[14+13] = 0; buf[14+14] = 0; buf[14+15] = 1;  // src
    buf[14+16] = 10; buf[14+17] = 0; buf[14+18] = 0; buf[14+19] = 2;  // dst
    f.set_data(buf, 32); f.set_sop(true); f.set_eop(true);
    in_1.write(f);
    auto outs = drain(out_1, 1);
    ELEM_ASSERT(outs.size() >= 0u, "parser run");

    h.run_for(50ms);
    ELEM_PASS("FlowTupleParser");
}
