// SPDX-License-Identifier: Apache-2.0
// Auto-generated behavioral test for element: Idle
//
// The kernel was generated by openclicknp-cc; we link it in via the
// CMake `openclicknp_element_test()` helper. The test spawns the kernel
// in a thread, drives canned flits through its input ports, and asserts
// on the resulting output stream.
#include "element_test_harness.hpp"

using namespace openclicknp;
using namespace openclicknp::test;

extern "C" void kernel_u(
    SwStream& out_1,
    std::atomic<bool>& _stop
);

int main() {
    SwStream out_1(64);

    KernelHarness h;
    h.start(kernel_u, std::ref(out_1), std::ref(h.stop));

    // Idle never produces.
    auto outs = drain(out_1, 1, 50ms);
    ELEM_ASSERT_EQ(outs.size(), 0u, "Idle must not produce");

    h.run_for(50ms);
    ELEM_PASS("Idle");
}
