// SPDX-License-Identifier: Apache-2.0
// Auto-generated behavioral test for element: FlitDemux
//
// The kernel was generated by openclicknp-cc; we link it in via the
// CMake `openclicknp_element_test()` helper. The test spawns the kernel
// in a thread, drives canned flits through its input ports, and asserts
// on the resulting output stream.
#include "element_test_harness.hpp"

using namespace openclicknp;
using namespace openclicknp::test;

extern "C" void kernel_u(
    SwStream& in_1,
    SwStream& out_1,
    SwStream& out_2,
    std::atomic<bool>& _stop
);

int main() {
    SwStream in_1(64);
    SwStream out_1(64);
    SwStream out_2(64);

    KernelHarness h;
    h.start(kernel_u, std::ref(in_1), std::ref(out_1), std::ref(out_2), std::ref(h.stop));

    // FlitDemux routes by lane 0 LSB.
    auto pusher = std::thread([&]() {
        in_1.write(make_flit(0));   // -> port 1
        in_1.write(make_flit(1));   // -> port 2
    });
    auto a = drain(out_1, 1); auto b = drain(out_2, 1);
    pusher.join();
    ELEM_ASSERT(a.size() + b.size() >= 1u, "FlitDemux should produce");

    h.run_for(50ms);
    ELEM_PASS("FlitDemux");
}
