// SPDX-License-Identifier: Apache-2.0
// Auto-generated behavioral test for element: Add2048
//
// The kernel was generated by openclicknp-cc; we link it in via the
// CMake `openclicknp_element_test()` helper. The test spawns the kernel
// in a thread, drives canned flits through its input ports, and asserts
// on the resulting output stream.
#include "element_test_harness.hpp"

using namespace openclicknp;
using namespace openclicknp::test;

extern "C" void kernel_u(
    SwStream& in_1,
    SwStream& in_2,
    SwStream& out_1,
    std::atomic<bool>& _stop
);

int main() {
    SwStream in_1(64);
    SwStream in_2(64);
    SwStream out_1(64);

    KernelHarness h;
    h.start(kernel_u, std::ref(in_1), std::ref(in_2), std::ref(out_1), std::ref(h.stop));

    auto pusher = std::thread([&]() { in_1.write(make_flit(10, 20, 30, 40)); in_2.write(make_flit(1, 2, 3, 4)); });
    auto outs = drain(out_1, 1);
    pusher.join();
    ELEM_ASSERT_EQ(outs.size(), 1u, "add");
    ELEM_ASSERT_EQ(outs[0].get(0), 11ull, "10+1");
    ELEM_ASSERT_EQ(outs[0].get(3), 44ull, "40+4");

    h.run_for(50ms);
    ELEM_PASS("Add2048");
}
