// SPDX-License-Identifier: Apache-2.0
// Auto-generated behavioral test for element: Pass
//
// The kernel was generated by openclicknp-cc; we link it in via the
// CMake `openclicknp_element_test()` helper. The test spawns the kernel
// in a thread, drives canned flits through its input ports, and asserts
// on the resulting output stream.
#include "element_test_harness.hpp"

using namespace openclicknp;
using namespace openclicknp::test;

extern "C" void kernel_u(
    SwStream& in_1,
    SwStream& out_1,
    std::atomic<bool>& _stop,
    SignalChannel& _sigch
);

int main() {
    SwStream in_1(64);
    SwStream out_1(64);

    KernelHarness h;
    h.start(kernel_u, std::ref(in_1), std::ref(out_1), std::ref(h.stop), std::ref(h.sigch));

    // Pass forwards every flit unchanged.
    auto outs = push_and_drain(in_1, out_1, {make_flit(0xA), make_flit(0xB), make_flit(0xC)}, 3);
    ELEM_ASSERT_EQ(outs.size(), 3u, "expected 3 flits");
    ELEM_ASSERT_EQ(outs[0].get(0), 0xAull, "lane 0 of flit 0");
    ELEM_ASSERT_EQ(outs[1].get(0), 0xBull, "lane 0 of flit 1");
    ELEM_ASSERT_EQ(outs[2].get(0), 0xCull, "lane 0 of flit 2");

    h.run_for(50ms);
    ELEM_PASS("Pass");
}
