// SPDX-License-Identifier: Apache-2.0
// Auto-generated behavioral test for element: FlitScheduler
//
// The kernel was generated by openclicknp-cc; we link it in via the
// CMake `openclicknp_element_test()` helper. The test spawns the kernel
// in a thread, drives canned flits through its input ports, and asserts
// on the resulting output stream.
#include "element_test_harness.hpp"

using namespace openclicknp;
using namespace openclicknp::test;

extern "C" void kernel_u(
    SwStream& in_1,
    SwStream& in_2,
    SwStream& in_3,
    SwStream& in_4,
    SwStream& out_1,
    std::atomic<bool>& _stop
);

int main() {
    SwStream in_1(64);
    SwStream in_2(64);
    SwStream in_3(64);
    SwStream in_4(64);
    SwStream out_1(64);

    KernelHarness h;
    h.start(kernel_u, std::ref(in_1), std::ref(in_2), std::ref(in_3), std::ref(in_4), std::ref(out_1), std::ref(h.stop));

    auto pusher = std::thread([&]() { in_1.write(make_flit(1)); in_2.write(make_flit(2)); in_3.write(make_flit(3)); in_4.write(make_flit(4)); });
    auto outs = drain(out_1, 4);
    pusher.join();
    ELEM_ASSERT(outs.size() >= 1u, "sched");

    h.run_for(50ms);
    ELEM_PASS("FlitScheduler");
}
