// SPDX-License-Identifier: Apache-2.0
// Auto-generated behavioral test for element: Tee
//
// The kernel was generated by openclicknp-cc; we link it in via the
// CMake `openclicknp_element_test()` helper. The test spawns the kernel
// in a thread, drives canned flits through its input ports, and asserts
// on the resulting output stream.
#include "element_test_harness.hpp"

using namespace openclicknp;
using namespace openclicknp::test;

extern "C" void kernel_u(
    SwStream& in_1,
    SwStream& out_1,
    SwStream& out_2,
    std::atomic<bool>& _stop
);

int main() {
    SwStream in_1(64);
    SwStream out_1(64);
    SwStream out_2(64);

    KernelHarness h;
    h.start(kernel_u, std::ref(in_1), std::ref(out_1), std::ref(out_2), std::ref(h.stop));

    // Tee duplicates each flit to both outputs.
    std::thread pusher([&]() {
        in_1.write(make_flit(42));
        in_1.write(make_flit(43));
    });
    auto a = drain(out_1, 2);
    auto b = drain(out_2, 2);
    pusher.join();
    ELEM_ASSERT_EQ(a.size(), 2u, "out_1 should have 2 flits");
    ELEM_ASSERT_EQ(b.size(), 2u, "out_2 should have 2 flits");
    ELEM_ASSERT_EQ(a[0].get(0), 42ull, "out_1[0]");
    ELEM_ASSERT_EQ(b[0].get(0), 42ull, "out_2[0]");

    h.run_for(50ms);
    ELEM_PASS("Tee");
}
