// SPDX-License-Identifier: Apache-2.0
// Auto-generated behavioral test for element: Subtract1024
//
// The kernel was generated by openclicknp-cc; we link it in via the
// CMake `openclicknp_element_test()` helper. The test spawns the kernel
// in a thread, drives canned flits through its input ports, and asserts
// on the resulting output stream.
#include "element_test_harness.hpp"

using namespace openclicknp;
using namespace openclicknp::test;

extern "C" void kernel_u(
    SwStream& in_1,
    SwStream& in_2,
    SwStream& out_1,
    std::atomic<bool>& _stop
);

int main() {
    SwStream in_1(64);
    SwStream in_2(64);
    SwStream out_1(64);

    KernelHarness h;
    h.start(kernel_u, std::ref(in_1), std::ref(in_2), std::ref(out_1), std::ref(h.stop));

    auto pusher = std::thread([&]() { in_1.write(make_flit(50, 100)); in_2.write(make_flit(20, 40)); });
    auto outs = drain(out_1, 1);
    pusher.join();
    ELEM_ASSERT_EQ(outs.size(), 1u, "subtract");
    ELEM_ASSERT_EQ(outs[0].get(0), 30ull, "50-20=30");

    h.run_for(50ms);
    ELEM_PASS("Subtract1024");
}
