// SPDX-License-Identifier: Apache-2.0
// Auto-generated behavioral test for element: MinHeap
//
// The kernel was generated by openclicknp-cc; we link it in via the
// CMake `openclicknp_element_test()` helper. The test spawns the kernel
// in a thread, drives canned flits through its input ports, and asserts
// on the resulting output stream.
#include "element_test_harness.hpp"

using namespace openclicknp;
using namespace openclicknp::test;

extern "C" void kernel_u(
    SwStream& in_1,
    SwStream& out_1,
    std::atomic<bool>& _stop
);

int main() {
    SwStream in_1(64);
    SwStream out_1(64);

    KernelHarness h;
    h.start(kernel_u, std::ref(in_1), std::ref(out_1), std::ref(h.stop));

    auto pusher = std::thread([&]() {
        in_1.write(make_flit(7)); in_1.write(make_flit(3)); in_1.write(make_flit(5));
    });
    auto outs = drain(out_1, 3);
    pusher.join();
    ELEM_ASSERT_EQ(outs.size(), 3u, "minheap");
    // Heap interleaves push/pop in the same cycle; we only check the
    // smallest item is one of the produced outputs.
    bool saw_min = false;
    for (auto& f : outs) if (f.get(0) == 3ull) saw_min = true;
    ELEM_ASSERT(saw_min, "heap should yield the minimum somewhere");

    h.run_for(50ms);
    ELEM_PASS("MinHeap");
}
