// SPDX-License-Identifier: Apache-2.0
// Auto-generated behavioral test for element: InfiniteSource
//
// The kernel was generated by openclicknp-cc; we link it in via the
// CMake `openclicknp_element_test()` helper. The test spawns the kernel
// in a thread, drives canned flits through its input ports, and asserts
// on the resulting output stream.
#include "element_test_harness.hpp"

using namespace openclicknp;
using namespace openclicknp::test;

extern "C" void kernel_u(
    SwStream& out_1,
    std::atomic<bool>& _stop
);

int main() {
    SwStream out_1(64);

    KernelHarness h;
    h.start(kernel_u, std::ref(out_1), std::ref(h.stop));

    auto outs = drain(out_1, 5, 200ms);
    ELEM_ASSERT(outs.size() >= 3u, "InfiniteSource should produce sequenced flits");
    if (outs.size() >= 2) {
        ELEM_ASSERT(outs[1].get(0) > outs[0].get(0), "sequence increments");
    }

    h.run_for(50ms);
    ELEM_PASS("InfiniteSource");
}
