// SPDX-License-Identifier: Apache-2.0
// Auto-generated behavioral test for element: GmemTableRead
//
// The kernel was generated by openclicknp-cc; we link it in via the
// CMake `openclicknp_element_test()` helper. The test spawns the kernel
// in a thread, drives canned flits through its input ports, and asserts
// on the resulting output stream.
#include "element_test_harness.hpp"

using namespace openclicknp;
using namespace openclicknp::test;

extern "C" void kernel_u(
    SwStream& in_1,
    SwStream& out_1,
    std::atomic<bool>& _stop
);

int main() {
    SwStream in_1(64);
    SwStream out_1(64);

    KernelHarness h;
    h.start(kernel_u, std::ref(in_1), std::ref(out_1), std::ref(h.stop));
auto outs = push_and_drain(in_1, out_1, {make_flit(0x99)}, 1); ELEM_ASSERT_EQ(outs.size(), 1u, "gmem read");
    h.run_for(50ms);
    ELEM_PASS("GmemTableRead");
}
