// SPDX-License-Identifier: Apache-2.0
// XRT host stub emitter.
//
// Produces:
//   generated/host/kernel_table.cpp     -- registry consumed by Platform
//   generated/host/<KernelName>.hpp     -- per-element C++ class

#include "openclicknp/passes.hpp"

#include <filesystem>
#include <fstream>
#include <set>
#include <sstream>

namespace openclicknp::backends {

namespace {

void emitKernelTable(std::ostream& os, const be::Build& b) {
    os << "// SPDX-License-Identifier: Apache-2.0\n"
       << "// Auto-generated by openclicknp-cc — DO NOT EDIT\n"
       << "#include \"openclicknp/platform.hpp\"\n";
    // Per-kernel headers.
    std::set<std::string> seen_types;
    for (const auto& k : b.kernels) seen_types.insert(k.element_type);
    for (const auto& t : seen_types) {
        os << "#include \"openclicknp/generated/" << t << ".hpp\"\n";
    }
    os << "\nnamespace openclicknp::generated {\n\n";
    os << "const KernelInfo kKernels[] = {\n";
    for (const auto& k : b.kernels) {
        os << "    { \"" << k.name << "\", \"" << k.element_type
           << "\", " << (k.has_signal ? "true" : "false")
           << ", " << (k.autorun ? "true" : "false")
           << ", " << k.axilite_base << " },\n";
    }
    os << "};\n";
    os << "const size_t kKernelCount = sizeof(kKernels)/sizeof(kKernels[0]);\n";
    os << "\nconst SignalEntry kSignalTable[] = {\n";
    for (const auto& s : b.signal_table) {
        os << "    { " << s.gid << ", \"" << s.kernel
           << "\", " << s.axilite_base << " },\n";
    }
    os << "};\n";
    os << "const size_t kSignalEntryCount = sizeof(kSignalTable)/sizeof(kSignalTable[0]);\n";
    os << "\nconst HostStreamEntry kHostStreams[] = {\n";
    for (const auto& h : b.host_streams) {
        os << "    { \"" << h.kernel << "\", " << h.port << ", "
           << (h.kernel_to_host ? "true" : "false") << ", "
           << h.slot_id << " },\n";
    }
    os << "};\n";
    os << "const size_t kHostStreamCount = sizeof(kHostStreams)/sizeof(kHostStreams[0]);\n";
    os << "\n}  // namespace openclicknp::generated\n";
}

void emitElementHeader(std::ostream& os, const be::KernelHls& k,
                       const std::string& type_name) {
    os << "// SPDX-License-Identifier: Apache-2.0\n"
       << "// Auto-generated element-class header for `" << type_name << "`\n"
       << "#pragma once\n"
       << "#include \"openclicknp/element.hpp\"\n\n"
       << "namespace openclicknp::generated {\n\n"
       << "class " << type_name << " : public openclicknp::Element {\n"
       << "public:\n"
       << "    " << type_name
       << "(openclicknp::Platform& p, std::string name)\n"
       << "        : openclicknp::Element(p, std::move(name)) {}\n";
    if (k.has_signal && !k.signal_params.empty()) {
        os << "\n    // Typed signal RPC derived from .signal arg list.\n";
        os << "    void invoke(";
        bool first = true;
        for (const auto& sp : k.signal_params) {
            if (!first) os << ", ";
            os << sp.type_name << " " << sp.field_name;
            first = false;
        }
        os << ") {\n"
           << "        openclicknp::SignalRequest req{};\n";
        // Marshal: place args into LParam[0..6] best-effort (uint64-each).
        size_t i = 0;
        for (const auto& sp : k.signal_params) {
            os << "        req.lparam[" << i << "] = static_cast<uint64_t>("
               << sp.field_name << ");\n";
            ++i;
            if (i >= 7) break;
        }
        os << "        signal(req);\n";
        os << "    }\n";
    }
    os << "};\n\n}  // namespace openclicknp::generated\n";
}

}  // namespace

bool emitXrtHost(const be::Build& build, const std::string& outdir,
                 DiagnosticEngine& d) {
    namespace fs = std::filesystem;
    fs::path dir = fs::path(outdir) / "host";
    fs::create_directories(dir);
    {
        std::ofstream f(dir / "kernel_table.cpp");
        if (!f) { d.error({}, "cannot write kernel_table.cpp"); return false; }
        emitKernelTable(f, build);
    }
    std::set<std::string> done;
    for (const auto& k : build.kernels) {
        if (done.count(k.element_type)) continue;
        done.insert(k.element_type);
        std::ofstream f(dir / (k.element_type + ".hpp"));
        if (!f) { d.error({}, "cannot write element header"); return false; }
        emitElementHeader(f, k, k.element_type);
    }
    return true;
}

}  // namespace openclicknp::backends
