// SPDX-License-Identifier: Apache-2.0
// Vitis HLS C++ backend.
//
// For each kernel, emits:
//   generated/kernels/<name>.cpp     -- HLS top function
//   generated/kernels/<name>_tb.cpp  -- C/RTL co-simulation testbench stub
//
// The kernel skeleton is:
//
//   void NAME(hls::stream<flit_t> &in_1, ..., hls::stream<flit_t> &out_1, ...,
//             [s_axilite signal regs if @]) {
//     #pragma HLS INTERFACE axis port=in_*
//     #pragma HLS INTERFACE axis port=out_*
//     #pragma HLS INTERFACE ap_ctrl_none port=return  // if autorun
//     static <state>
//     <init body, guarded by static bool>
//     while (1) {
//       #pragma HLS PIPELINE II=1
//       <prologue: read input ports / signal>
//       <handler body | signal body>
//       <epilogue: write output ports>
//     }
//   }

#include "openclicknp/passes.hpp"
#include "../body_rewrite.hpp"

#include <filesystem>
#include <fstream>
#include <sstream>

namespace openclicknp::backends {

namespace {

void emitPrologueComment(std::ostream& os, const be::Build& build,
                         const be::KernelHls& k) {
    os << "// SPDX-License-Identifier: Apache-2.0\n"
       << "// Auto-generated by openclicknp-cc — DO NOT EDIT\n"
       << "// Kernel:        " << k.name << "\n"
       << "// Element type:  " << k.element_type << "\n"
       << "// Source:        " << build.source_path << "\n"
       << "// Platform:      " << be::platformName(build.platform) << "\n\n";
}

void emitIncludes(std::ostream& os) {
    os << "#include <ap_int.h>\n"
       << "#include <ap_axi_sdata.h>\n"
       << "#include <hls_stream.h>\n"
       << "#include \"openclicknp/hls_runtime.hpp\"\n\n";
}

std::string portList(const be::KernelHls& k) {
    std::ostringstream os;
    bool first = true;
    auto comma = [&]() { if (!first) os << ",\n    "; first = false; };
    for (const auto& p : k.in_ports) {
        comma();
        os << "hls::stream<openclicknp::flit_t>& in_" << p.index;
    }
    for (const auto& p : k.out_ports) {
        comma();
        os << "hls::stream<openclicknp::flit_t>& out_" << p.index;
    }
    if (k.has_signal) {
        comma();
        os << "openclicknp::SignalIO& sig_io";
    }
    return os.str();
}

void emitInterfacePragmas(std::ostream& os, const be::KernelHls& k) {
    for (const auto& p : k.in_ports)
        os << "#pragma HLS INTERFACE axis port=in_" << p.index << "\n";
    for (const auto& p : k.out_ports)
        os << "#pragma HLS INTERFACE axis port=out_" << p.index << "\n";
    if (k.has_signal) {
        // Pass the SignalIO struct as an s_axilite port; HLS synthesizes
        // each field as its own register (no pointer arithmetic).
        os << "#pragma HLS INTERFACE s_axilite port=sig_io"
           << " bundle=control offset=" << std::hex << "0x"
           << k.axilite_base << std::dec << "\n";
        os << "#pragma HLS INTERFACE s_axilite port=return bundle=control\n";
        os << "#pragma HLS DATA_PACK variable=sig_io\n";
    } else if (k.autorun) {
        os << "#pragma HLS INTERFACE ap_ctrl_none port=return\n";
    } else {
        os << "#pragma HLS INTERFACE s_axilite port=return bundle=control\n";
    }
}

void emitKernel(std::ostream& os, const be::Build& build,
                const be::KernelHls& k) {
    emitPrologueComment(os, build, k);
    emitIncludes(os);

    // Emit per-kernel state as a file-scope struct so `static constexpr`
    // members are legal and user code can reference them as `_state.NAME`.
    if (!k.state_cpp.empty()) {
        os << "namespace { namespace " << k.name << "_ns {\n";
        os << "    using namespace openclicknp;\n";
        os << "    struct State_t {\n";
        std::istringstream is(k.state_cpp);
        std::string line;
        while (std::getline(is, line)) {
            std::string l = line;
            size_t pos = l.find("constexpr");
            if (pos != std::string::npos &&
                (pos == 0 || l[pos-1] == ' ' || l[pos-1] == '\t') &&
                l.find("static") == std::string::npos) {
                l.replace(pos, std::string("constexpr").size(), "static constexpr");
            }
            os << "        " << l << "\n";
        }
        os << "    };\n";
        os << "} }\n\n";
    }

    os << "extern \"C\" void " << k.name << "(\n    "
       << portList(k) << ")\n{\n";

    emitInterfacePragmas(os, k);
    os << "\n";

    // Make all OpenClickNP constants visible without qualification inside
    // user element bodies (e.g. OPENCLICKNP_PAYLOAD_BYTES).
    os << "    using namespace openclicknp;\n";

    // State persists across handler iterations. The struct itself is at
    // file scope (above) so `static constexpr` members are legal; we
    // bring it into the function via a `using` alias so user code may
    // refer to it as `State_t`.
    os << "    // ---- state ----\n";
    if (!k.state_cpp.empty()) {
        os << "    using State_t = " << k.name << "_ns::State_t;\n";
        os << "    static State_t _state;\n";
    }
    os << "    static bool _inited = false;\n\n";

    // Init block (one-shot)
    if (!k.init_cpp.empty()) {
        os << "    if (!_inited) {\n";
        std::istringstream is(k.init_cpp);
        std::string line;
        while (std::getline(is, line)) os << "        " << line << "\n";
        os << "        _inited = true;\n";
        os << "    }\n\n";
    } else {
        os << "    _inited = true;\n\n";
    }

    // Per-iteration handler.
    os << "    // ---- handler loop ----\n";
    os << "    openclicknp::port_mask_t _ret = openclicknp::PORT_ALL;\n";
    os << "    openclicknp::port_mask_t _input_port = 0, "
                   "_output_port = 0, _output_failed = 0, _output_success = 0;\n";
    os << "    openclicknp::flit_t _input_data[OPENCLICKNP_MAX_PORTS+1];\n";
    os << "    openclicknp::flit_t _output_data[OPENCLICKNP_MAX_PORTS+1];\n";
    if (k.has_signal) {
        os << "    openclicknp::ClSignal event{}, outevent{};\n";
        os << "    bool _has_signal = false;\n";
    }
    os << "\n    while (true) {\n";
    os << "#pragma HLS PIPELINE II=1\n";

    if (k.has_signal) {
        os << "        // signal poll (host-controlled element)\n";
        os << "        if (!_has_signal) {\n";
        os << "            _has_signal = openclicknp::poll_signal(sig_io, &event);\n";
        os << "        }\n";
    }

    // Read inputs.
    os << "        // read inputs\n";
    for (const auto& p : k.in_ports) {
        os << "        if ((_ret & openclicknp::PORT_BIT(" << p.index
           << ")) && !(_input_port & openclicknp::PORT_BIT(" << p.index
           << "))) {\n"
           << "            openclicknp::flit_t f; if (in_" << p.index
           << ".read_nb(f)) {\n"
           << "                _input_data[" << p.index << "] = f;\n"
           << "                _input_port |= openclicknp::PORT_BIT("
           << p.index << ");\n"
           << "            }\n        }\n";
    }
    os << "        _output_port = 0;\n";
    os << "        openclicknp::port_mask_t last_rport = _ret;\n";

    if (k.has_signal) {
        os << "        if (_has_signal) {\n";
        os << "            outevent = event;\n";
        os << "            // ---- user .signal body ----\n";
        std::string sig = rewriteReturns(k.signal_cpp, "signal");
        std::istringstream is(sig);
        std::string line;
        while (std::getline(is, line)) os << "            " << line << "\n";
        os << "            _end_signal: ;\n";
        os << "            openclicknp::respond_signal(sig_io, outevent);\n";
        os << "            _has_signal = false;\n";
        os << "        } else {\n";
    }

    os << "        // ---- user .handler body ----\n";
    {
        std::string h = rewriteReturns(k.handler_cpp, "handler");
        std::istringstream is(h);
        std::string line;
        while (std::getline(is, line)) os << "        " << line << "\n";
    }
    os << "        _end_handler: ;\n";

    // Write outputs.
    os << "        _output_failed = _output_success = 0;\n";
    for (const auto& p : k.out_ports) {
        os << "        if (_output_port & openclicknp::PORT_BIT(" << p.index
           << ")) {\n"
           << "            bool ok = out_" << p.index
           << ".write_nb(_output_data[" << p.index << "]);\n"
           << "            if (ok) _output_success |= openclicknp::PORT_BIT("
           << p.index << ");\n"
           << "            else    _output_failed  |= openclicknp::PORT_BIT("
           << p.index << ");\n"
           << "        }\n";
    }
    if (k.has_signal) os << "        }\n";

    os << "    }\n";
    os << "}\n";
}

void emitTestbench(std::ostream& os, const be::Build& build,
                   const be::KernelHls& k) {
    os << "// SPDX-License-Identifier: Apache-2.0\n"
       << "// Auto-generated cosim testbench for " << k.name << "\n"
       << "#include <hls_stream.h>\n"
       << "#include \"openclicknp/hls_runtime.hpp\"\n\n";
    os << "extern \"C\" void " << k.name << "(\n    "
       << portList(k) << ");\n\n";
    os << "int main() {\n";
    for (const auto& p : k.in_ports)
        os << "    hls::stream<openclicknp::flit_t> in_" << p.index << ";\n";
    for (const auto& p : k.out_ports)
        os << "    hls::stream<openclicknp::flit_t> out_" << p.index << ";\n";
    if (k.has_signal)
        os << "    static openclicknp::SignalIO sig_io = {};\n";

    // Drive a dummy SOP/EOP flit through input port 1 if any.
    if (!k.in_ports.empty()) {
        os << "    openclicknp::flit_t f{}; f.set(0, 0xCAFEBABEULL); "
           << "f.set_sop(true); f.set_eop(true);\n";
        os << "    in_1.write(f);\n";
    }
    os << "    " << k.name << "(\n        ";
    bool first = true;
    auto comma = [&]() { if (!first) os << ", "; first = false; };
    for (const auto& p : k.in_ports)  { comma(); os << "in_"  << p.index; }
    for (const auto& p : k.out_ports) { comma(); os << "out_" << p.index; }
    if (k.has_signal) { comma(); os << "sig_io"; }
    os << ");\n";
    os << "    return 0;\n}\n";
    (void)build;
}

}  // namespace

bool emitHlsCpp(const be::Build& build, const std::string& outdir,
                DiagnosticEngine& d) {
    namespace fs = std::filesystem;
    fs::path kdir = fs::path(outdir) / "kernels";
    fs::create_directories(kdir);
    bool ok = true;
    for (const auto& k : build.kernels) {
        fs::path p   = kdir / (k.name + ".cpp");
        fs::path tbp = kdir / (k.name + "_tb.cpp");
        std::ofstream f(p);
        if (!f) { d.error({}, "cannot write " + p.string()); ok = false; continue; }
        emitKernel(f, build, k);
        std::ofstream tb(tbp);
        if (tb) emitTestbench(tb, build, k);
    }

    // Also emit a CMakeLists.txt that the build scripts can use to discover
    // the per-kernel sources.
    std::ofstream cm(fs::path(outdir) / "kernels" / "CMakeLists.txt");
    if (cm) {
        cm << "# Auto-generated kernel manifest\n";
        for (const auto& k : build.kernels) {
            cm << "openclicknp_register_kernel(" << k.name << ")\n";
        }
    }
    return ok;
}

}  // namespace openclicknp::backends
