// SPDX-License-Identifier: Apache-2.0
// Element base class. Per-kernel subclasses are auto-generated by the
// XRT host stub backend.
#pragma once

#include "openclicknp/platform.hpp"

#include <functional>
#include <string>

namespace openclicknp {

class Element {
public:
    Element(Platform& p, std::string name) : platform_(p), name_(std::move(name)) {}
    virtual ~Element() = default;

    // Launch the kernel (no-op for autorun).
    virtual void launch();

    // Stop-and-wait host→kernel signal RPC.
    virtual bool signal(const SignalRequest& req, SignalResponse& rsp,
                        int timeout_ms = 1000);
    SignalResponse signal(const SignalRequest& req, int timeout_ms = 1000) {
        SignalResponse r{};
        signal(req, r, timeout_ms);
        return r;
    }

    // Streaming host_in/host_out interface.
    virtual void send(const HostMessage& msg);
    virtual bool receive(HostMessage& msg, bool blocking = true);

    // Async receive callback (invoked on a worker thread).
    using Callback = std::function<void(const HostMessage&)>;
    virtual void setCallback(Callback cb);

    [[nodiscard]] const std::string& name() const noexcept { return name_; }
    [[nodiscard]] Platform& platform() const noexcept { return platform_; }

protected:
    Platform&   platform_;
    std::string name_;
    Callback    callback_;
};

}  // namespace openclicknp
