// SPDX-License-Identifier: Apache-2.0
// Software-emulator runtime: bounded SPSC FIFOs + signal channels.
//
// This header is meant to be `#include`d by code generated by the SW emu
// backend AND by L1 unit-test harnesses. It provides the *exact* same
// macro-level API used by the HLS C++ backend, so element bodies are
// source-compatible across both targets.
#pragma once

#include "openclicknp/flit.hpp"

#include <atomic>
#include <chrono>
#include <condition_variable>
#include <cstring>
#include <deque>
#include <mutex>
#include <thread>
#include <vector>

namespace openclicknp {

// ----------------------------------------------------------------------------
// SwStream: bounded SPSC FIFO of flit_t.
// ----------------------------------------------------------------------------
class SwStream {
public:
    explicit SwStream(int capacity)
        : capacity_(capacity > 0 ? capacity : 1) {}

    // Non-blocking write. Returns false if the buffer is full.
    bool write_nb(const flit_t& f) {
        std::lock_guard<std::mutex> lk(m_);
        if (static_cast<int>(q_.size()) >= capacity_) return false;
        q_.push_back(f);
        cv_.notify_one();
        return true;
    }

    // Blocking write.
    void write(const flit_t& f) {
        while (!write_nb(f)) {
            std::this_thread::yield();
        }
    }

    // Non-blocking read.
    bool read_nb(flit_t& out) {
        std::lock_guard<std::mutex> lk(m_);
        if (q_.empty()) return false;
        out = q_.front();
        q_.pop_front();
        return true;
    }

    // Blocking read.
    flit_t read() {
        std::unique_lock<std::mutex> lk(m_);
        cv_.wait(lk, [&]{ return !q_.empty(); });
        flit_t f = q_.front();
        q_.pop_front();
        return f;
    }

    int size() {
        std::lock_guard<std::mutex> lk(m_);
        return static_cast<int>(q_.size());
    }
    bool empty() { return size() == 0; }
    int capacity() const { return capacity_; }

    // Sentinel "null" stream — used in auto-generated harness placeholders.
    // Reads always fail, writes always succeed silently.
    static SwStream& null() {
        static SwStream s(1);
        return s;
    }

private:
    std::mutex m_;
    std::condition_variable cv_;
    std::deque<flit_t> q_;
    int capacity_;
};

// ----------------------------------------------------------------------------
// SignalChannel: bidirectional event / response queue per signal-enabled
// kernel. Used by the SW emulator to mock the AXI-Lite RPC.
// ----------------------------------------------------------------------------
class SignalChannel {
public:
    bool try_recv(ClSignal& out) {
        std::lock_guard<std::mutex> lk(m_);
        if (req_.empty()) return false;
        out = req_.front();
        req_.pop_front();
        return true;
    }
    void send_response(const ClSignal& s) {
        std::lock_guard<std::mutex> lk(m_);
        rsp_.push_back(s);
        cv_.notify_all();
    }
    void post_request(const ClSignal& s) {
        std::lock_guard<std::mutex> lk(m_);
        req_.push_back(s);
        cv_.notify_all();
    }
    bool wait_response(ClSignal& out, int timeout_ms) {
        std::unique_lock<std::mutex> lk(m_);
        if (!cv_.wait_for(lk, std::chrono::milliseconds(timeout_ms),
                          [&]{ return !rsp_.empty(); })) return false;
        out = rsp_.front();
        rsp_.pop_front();
        return true;
    }
    static SignalChannel& dummy() { static SignalChannel s; return s; }
private:
    std::mutex m_;
    std::condition_variable cv_;
    std::deque<ClSignal> req_, rsp_;
};

// ----------------------------------------------------------------------------
// Macro stubs the HLS backend defines as inline ports. The SW emulator just
// uses them as plain expressions. Defined in flit.hpp.
// ----------------------------------------------------------------------------

}  // namespace openclicknp
